### PR TITLE
Add flag to open QS instantly in the webbrowser

### PR DESCRIPTION
**Pull request by jvfe**
- docs: Add correct command in README
- feat: Add flag to open browser with QuickStatements
- style: Sort imports on src/

### CODE REVIEW

**Comment by cthoyt** [comment]
@jvfe this is great! you could consider adding the following to `pyproject.toml` to make `isort` do this automatically for you:

```toml
[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100
include_trailing_comma = true
reverse_relative = true
```

**Comment by jvfe** [comment]
> @jvfe this is great! you could consider adding the following to `pyproject.toml` to make `isort` and `black` have an explicit styling:
> 
> ```toml
> [tool.black]
> line-length = 100
> target-version = ["py37", "py38", "py39", "py310"]
> 
> [tool.isort]
> profile = "black"
> multi_line_output = 3
> line_length = 100
> include_trailing_comma = true
> reverse_relative = true
> ```

Hi, thank you! I've added that to the TOML file.

**Comment by jvfe** [comment]
BTW, had to do some ugly rebasing + squashing to fix the conflicts after 52550f23bc62c590c4c790aed9789fd7372d0972 - hence the force pushes - but the this PR's commit history is still the same and I don't believe I've broken anything.

**Comment by cthoyt** [comment]
The simple solution for projects with more than one contributor is to always use "squash and merge" which turns all commits in a PR into exactly one commit in the main branch.

**Pull request merged**
